spring.application.name=MyLunarCore

logging.file.path=logs

server.port=8080

server.ssl.enabled=false
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12



lunarcore.netty.port=9000

lunarcore.netty.business-threads=0

lunarcore.game-tcp-enabled=true

lunarcore.tls.game-tcp-enabled=false
lunarcore.tls.key-store=classpath:keystore.p12
lunarcore.tls.key-store-password=changeit
lunarcore.tls.key-store-type=PKCS12
lunarcore.tls.key-password=changeit

lunarcore.game-kcp-enabled=true

lunarcore.kcp.interval=20

lunarcore.kcp.mtu=1400


lunarcore.game-loop.enabled=true

lunarcore.game-loop.period-ms=1000
lunarcore.activity-schedule-resource=classpath:data/ActivityScheduling.json


lunarcore.hotfix.resource=classpath:hotfix.json

lunarcore.reload-console-enabled=true


lunarcore.session.timeout-seconds=60

lunarcore.session.max-online-players=0


lunarcore.sync.passive-interval-ms=60000

lunarcore.sync.async-load-threads=0
lunarcore.sync.async-load-queue-capacity=1024

lunarcore.sync.periodic-persistence-enabled=true
lunarcore.sync.periodic-persistence-interval-ms=30000

spring.datasource.url=jdbc:mysql://localhost:3306/lunarcore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
