spring.sql.init.mode=never
lunarcore.reload-console-enabled=false
lunarcore.game-tcp-enabled=false
lunarcore.game-kcp-enabled=false
lunarcore.game-loop.enabled=false
lunarcore.sync.periodic-persistence-enabled=false
lunarcore.redis.enabled=false
