server:
  port: 18082

spring:
  application:
    name: player-service
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension:yaml}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
      config:
        namespace: ${NACOS_NAMESPACE:public}
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: health,info
